In [151]:
import pandas as pd
import numpy as np

In [152]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("CooperUnion/anime-recommendations-database")

In [153]:
df = pd.read_csv(path + "/anime.csv")

In [154]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [155]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [156]:
df.loc[5] ["rating"]

np.float64(9.15)

In [157]:
def rating_count(rating):
    if rating >= 9:
        return "Excellent"
    if rating >= 8:
        return "Good"
    if rating >= 7:
        return "Average"
    else:
        return "Poor"

In [158]:
df["rating_category"] = df["rating"].apply(rating_count)

In [159]:
df

,anime_id,name,genre,type,episodes,rating,members,rating_category
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Excellent
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Excellent
...,...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,Poor
12290,5543,Under World,Hentai,OVA,1,4.28,183,Poor
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,Poor
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,Poor
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,Poor

In [160]:
excellent_anime = df[df["rating_category"] == "Excellent"]
excellent_anime

,anime_id,name,genre,type,episodes,rating,members,rating_category
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Excellent
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Excellent
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351,Excellent
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855,Excellent
7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679,Excellent
8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534,Excellent
9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109,Excellent
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749,Excellent
11,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733,Excellent
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376,Excellent
9078,33607,Kahei no Umi,Historical,Movie,1,9.33,44,Excellent
9539,26259,Mienu Me ni Kanjita Kumotoriyama no Asahi,"Drama, Kids",OVA,1,9.00,47,Excellent
9577,33980,Mirai ni Mukete: Bousai wo Kangaeru,Drama,Movie,1,9.00,77,Excellent
9595,23005,Mogura no Motoro,Slice of Life,Movie,1,9.50,62,Excellent
9831,26145,Okaachan Gomen ne,"Historical, Kids",Movie,1,9.00,47,Excellent
10136,34191,Santa-san wa Dai Isogashi,"Fantasy, Kids",OVA,1,9.00,25,Excellent
10181,32627,Shaka no Shougai,Historical,Movie,1,9.00,31,Excellent
10191,32796,Shenmi Shijie Lixian Ji,"Adventure, Comedy, Fantasy",Movie,1,9.00,37,Excellent
10400,30120,Spoon-hime no Swing Kitchen,"Adventure, Kids",TV,Unknown,9.60,47,Excellent
10464,33662,Taka no Tsume 8: Yoshida-kun no X-Files,"Comedy, Parody",Movie,1,10.00,13,Excellent
10786,26313,Yakusoku: Africa Mizu to Midori,"Drama, Kids",OVA,1,9.25,53,Excellent

In [161]:
poor_anime = df[df["rating_category"] == "Poor"]
poor_anime

,anime_id,name,genre,type,episodes,rating,members,rating_category
3426,6479,Candy Boy Episode: EX02 - Shiawase Kyouyuu Riron,"Romance, Shoujo Ai, Slice of Life",Special,1,6.99,15078,Poor
3427,2274,CLAMP in Wonderland,Music,Music,1,6.99,12267,Poor
3428,1841,Dai Mahou Touge Omake,Comedy,Special,4,6.99,5579,Poor
3429,292,Dear Boys,"Drama, Shounen, Sports",TV,26,6.99,12662,Poor
3430,896,Dragon Ball Z Movie 03: Chikyuu Marugoto Chouk...,"Adventure, Comedy, Fantasy, Sci-Fi, Shounen",Movie,1,6.99,57840,Poor
...,...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,Poor
12290,5543,Under World,Hentai,OVA,1,4.28,183,Poor
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,Poor
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,Poor
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,Poor

In [162]:
avg_anime = df[df['rating_category'] == "Average"]
avg_anime

,anime_id,name,genre,type,episodes,rating,members,rating_category
534,996,Bishoujo Senshi Sailor Moon: Sailor Stars,"Adventure, Comedy, Drama, Fantasy, Magic, Roma...",TV,34,7.99,52586,Average
535,9465,Break Blade 4: Sanka no Chi,"Action, Fantasy, Mecha, Military, Shounen",Movie,1,7.99,41598,Average
536,14175,Hanasaku Iroha: Home Sweet Home,"Comedy, Drama, Slice of Life",Movie,1,7.99,34630,Average
537,11239,Hidamari Sketch x Honeycomb,"Comedy, School, Slice of Life",TV,12,7.99,12590,Average
538,967,Hokuto no Ken,"Action, Drama, Martial Arts, Sci-Fi, Shounen",TV,109,7.99,40271,Average
...,...,...,...,...,...,...,...,...
11237,30898,Tsunpri,Hentai,OVA,1,7.02,2362,Average
11238,2852,Accelerando: Datenshi-tachi no Sasayaki,Hentai,OVA,4,7.00,7484,Average
11239,5719,Sex Pistols,"Comedy, Drama, Supernatural, Yaoi",OVA,2,7.00,15885,Average
11240,10488,Shocking Pink!,"Harem, Hentai",OVA,2,7.00,3877,Average
11241,21363,Tokubetsu Jugyou 3 SLG The Animation,Hentai,OVA,2,7.00,2601,Average

In [163]:
df

,anime_id,name,genre,type,episodes,rating,members,rating_category
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Excellent
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Excellent
...,...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,Poor
12290,5543,Under World,Hentai,OVA,1,4.28,183,Poor
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,Poor
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,Poor
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,Poor

In [164]:
rating_mean = df["rating"].mean()

In [165]:
rating_mean

np.float64(6.473901690981432)

In [166]:
best_to_watch_rating_wise = df[df["rating"] > rating_mean]
best_to_watch_rating_wise

,anime_id,name,genre,type,episodes,rating,members,rating_category
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Excellent
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Excellent
...,...,...,...,...,...,...,...,...
11522,6685,Mesu Kyoushi: Injoku no Kyoushitsu,Hentai,OVA,3,6.48,2005,Poor
11523,6220,Musuko no Tomodachi ni Okasarete,Hentai,OVA,2,6.48,1883,Poor
11524,31400,Rinkan Biyaku Chuudoku: Nigeba Nashi! 1428-nin...,Hentai,OVA,2,6.48,2327,Poor
11525,5993,Samayou Midara na Lunatics,Hentai,OVA,2,6.48,1916,Poor
12251,33960,Chou Do M na Hentai Mesu-tachi Otokoton Chouky...,Hentai,OVA,Unknown,8.38,161,Good

In [167]:
members_mean = df["members"].mean()
members_mean

np.float64(18071.33886448674)

In [168]:
best_to_watch_members_rating_mean_wise = df[(df["rating"] > rating_mean) & (df["members"] > members_mean)]
best_to_watch_members_rating_mean_wise

,anime_id,name,genre,type,episodes,rating,members,rating_category
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Excellent
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Excellent
...,...,...,...,...,...,...,...,...
11222,741,Sensitive Pornograph,"Comedy, Drama, Hentai, Romance, Yaoi",OVA,1,7.06,27518,Average
11233,3375,Kirepapa.,"Comedy, Drama, Romance, Yaoi",OVA,2,7.02,30628,Average
11288,368,Bible Black,Hentai,OVA,6,6.88,31309,Poor
11380,320,A Kite,"Action, Drama, Hentai, Police",OVA,2,6.72,27941,Poor
11461,2148,Okane ga Nai,"Drama, Romance, Yaoi",OVA,4,6.58,27367,Poor

In [169]:
# This groups the data by type and calculates the mean rating for each
df.groupby("type")["rating"].mean()

type
Movie      6.318058
Music      5.588996
ONA        5.643298
OVA        6.375221
Special    6.523501
TV         6.902299
Name: rating, dtype: float64

In [170]:
top_anime = df.sort_values(by ="rating", ascending = False).head(10) 
top_anime

,anime_id,name,genre,type,episodes,rating,members,rating_category
10464,33662,Taka no Tsume 8: Yoshida-kun no X-Files,"Comedy, Parody",Movie,1,10.00,13,Excellent
10400,30120,Spoon-hime no Swing Kitchen,"Adventure, Kids",TV,Unknown,9.60,47,Excellent
9595,23005,Mogura no Motoro,Slice of Life,Movie,1,9.50,62,Excellent
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,Excellent
9078,33607,Kahei no Umi,Historical,Movie,1,9.33,44,Excellent
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,Excellent
10786,26313,Yakusoku: Africa Mizu to Midori,"Drama, Kids",OVA,1,9.25,53,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,Excellent

In [171]:
popular_anime = df.sort_values(by = "members" , ascending = False).head(100)

top_famous = popular_anime.sort_values(by= "rating", ascending = False).head(100)

top_famous

,anime_id,name,genre,type,episodes,rating,members,rating_category
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,Excellent
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,Excellent
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855,Excellent
10,4181,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24,9.06,456749,Excellent
12,918,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376,Excellent
...,...,...,...,...,...,...,...,...
1598,8769,Ore no Imouto ga Konnani Kawaii Wake ga Nai,"Comedy, Seinen, Slice of Life",TV,12,7.49,321477,Average
1620,6880,Deadman Wonderland,"Action, Horror, Sci-Fi",TV,12,7.48,453454,Average
1709,8074,Highschool of the Dead,"Action, Ecchi, Horror, Supernatural",TV,12,7.46,535892,Average
1779,20787,Black Bullet,"Action, Mystery, Sci-Fi, Seinen",TV,13,7.44,320267,Average
2132,21881,Sword Art Online II,"Action, Adventure, Fantasy, Game, Romance",TV,24,7.35,537892,Average

In [172]:
print(top_famous[['name', 'genre', 'type', 'episodes', 'rating', 'members']].head(100).to_string())

                                                          name                                                                     genre   type episodes  rating  members
1                             Fullmetal Alchemist: Brotherhood               Action, Adventure, Drama, Fantasy, Magic, Military, Shounen     TV       64    9.26   793665
3                                                  Steins;Gate                                                          Sci-Fi, Thriller     TV       24    9.17   673572
6                                       Hunter x Hunter (2011)                                   Action, Adventure, Shounen, Super Power     TV      148    9.13   425855
10                                        Clannad: After Story                      Drama, Fantasy, Romance, Slice of Life, Supernatural     TV       24    9.06   456749
12                                                     Gintama              Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen     TV      201    9.04   336376
13                          Code Geass: Hangyaku no Lelouch R2                       Action, Drama, Mecha, Military, Sci-Fi, Super Power     TV       25    8.98   572888
15                               Sen to Chihiro no Kamikakushi                                            Adventure, Drama, Supernatural  Movie        1    8.93   466254
16                                     Shigatsu wa Kimi no Uso                                    Drama, Music, Romance, School, Shounen     TV       22    8.92   416397
19                             Code Geass: Hangyaku no Lelouch                      Action, Mecha, Military, School, Sci-Fi, Super Power     TV       25    8.83   715151
22                                                Cowboy Bebop                           Action, Adventure, Comedy, Drama, Sci-Fi, Space     TV       26    8.82   486824
23                                               One Punch Man         Action, Comedy, Parody, Sci-Fi, Seinen, Super Power, Supernatural     TV       12    8.82   552458
24                                               Mononoke Hime                                                Action, Adventure, Fantasy  Movie        1    8.81   339556
29                                  Tengen Toppa Gurren Lagann                                  Action, Adventure, Comedy, Mecha, Sci-Fi     TV       27    8.78   562962
35                                         Howl no Ugoku Shiro                                        Adventure, Drama, Fantasy, Romance  Movie        1    8.74   333186
36                                        Fate/Zero 2nd Season                                   Action, Fantasy, Supernatural, Thriller     TV       12    8.73   340973
40                                                  Death Note                    Mystery, Police, Psychological, Supernatural, Thriller     TV       37    8.71  1013917
49                                     Boku dake ga Inai Machi                              Mystery, Psychological, Seinen, Supernatural     TV       12    8.65   402381
54                       Re:Zero kara Hajimeru Isekai Seikatsu                                   Drama, Fantasy, Psychological, Thriller     TV       25    8.64   355839
57    Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.                                        Drama, Slice of Life, Supernatural     TV       11    8.62   463835
61                                          Shokugeki no Souma                                                    Ecchi, School, Shounen     TV       24    8.61   348951
67                                  Kiseijuu: Sei no Kakuritsu                      Action, Drama, Horror, Psychological, Sci-Fi, Seinen     TV       24    8.59   425457
74                                                   One Piece           Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power     TV  Unknown    8.58   504862
86                                          Shingeki no Kyojin                              Action, Drama, Fantasy, Shounen, Super Power     TV       25    8.54   896229
84                                                    Baccano!                 Action, Comedy, Historical, Mystery, Seinen, Supernatural     TV       13    8.54   363215
96                                  Mahou Shoujo Madoka★Magica                                     Drama, Magic, Psychological, Thriller     TV       12    8.51   462974
94                                                   Fate/Zero                                             Action, Fantasy, Supernatural     TV       13    8.51   453630
104                                           Samurai Champloo                   Action, Adventure, Comedy, Historical, Samurai, Shounen     TV       26    8.50   390076
98                                                 Psycho-Pass                                     Action, Police, Psychological, Sci-Fi     TV       22    8.50   509109
118                                            No Game No Life                     Adventure, Comedy, Ecchi, Fantasy, Game, Supernatural     TV       12    8.47   602291
122                                           Kuroko no Basket                                           Comedy, School, Shounen, Sports     TV       25    8.46   338315
131                                                  Toradora!                                    Comedy, Romance, School, Slice of Life     TV       25    8.45   633817
141                                          Nanatsu no Taizai                  Action, Adventure, Ecchi, Fantasy, Shounen, Supernatural     TV       24    8.42   331627
158                                 Sakurasou no Pet na Kanojo                             Comedy, Drama, Romance, School, Slice of Life     TV       24    8.40   380375
159                                               Angel Beats!                               Action, Comedy, Drama, School, Supernatural     TV       13    8.39   717796
160                                             Bakemonogatari                                   Mystery, Romance, Supernatural, Vampire     TV       15    8.39   482268
164                                     Ouran Koukou Host Club                                    Comedy, Harem, Romance, School, Shoujo     TV       26    8.39   422271
166                                                 Durarara!!                                             Action, Mystery, Supernatural     TV       24    8.38   556431
177                                      Ookami to Koushinryou                                   Adventure, Fantasy, Historical, Romance     TV       13    8.37   334932
199                                               Death Parade                             Drama, Game, Mystery, Psychological, Thriller     TV       12    8.33   383914
200                                        Fullmetal Alchemist       Action, Adventure, Comedy, Drama, Fantasy, Magic, Military, Shounen     TV       51    8.33   600384
211                                    Neon Genesis Evangelion                     Action, Dementia, Drama, Mecha, Psychological, Sci-Fi     TV       26    8.32   461946
206                                              Dragon Ball Z    Action, Adventure, Comedy, Fantasy, Martial Arts, Shounen, Super Power     TV      291    8.32   375662
223                                                    Clannad               Comedy, Drama, Romance, School, Slice of Life, Supernatural     TV       23    8.30   566690
248                                      Kaichou wa Maid-sama!                                           Comedy, Romance, School, Shoujo     TV       26    8.26   391628
250                                          Zankyou no Terror                                                   Psychological, Thriller     TV       11    8.26   342893
251                      Darker than Black: Kuro no Keiyakusha                                      Action, Mystery, Sci-Fi, Super Power     TV       25    8.25   440334
268                               Magi: The Labyrinth of Magic                                Action, Adventure, Fantasy, Magic, Shounen     TV       25    8.24   317513
281                                               Kill la Kill                                       Action, Comedy, School, Super Power     TV       24    8.23   508118
288                                                 Fairy Tail                        Action, Adventure, Comedy, Fantasy, Magic, Shounen     TV      175    8.22   584590
304                                                 D.Gray-man                                        Action, Adventure, Comedy, Shounen     TV      103    8.20   334399
301                                    Ansatsu Kyoushitsu (TV)                                           Action, Comedy, School, Shounen     TV       22    8.20   312654
319                                             Kimi ni Todoke                                    Romance, School, Shoujo, Slice of Life     TV       25    8.19   309339
334                                  Higurashi no Naku Koro ni                    Horror, Mystery, Psychological, Supernatural, Thriller     TV       26    8.17   359494
335                                                     Hyouka                                            Mystery, School, Slice of Life     TV       22    8.17   372246
331                                               Black Lagoon                                                            Action, Seinen     TV       12    8.17   332562
339                                                   Noragami                                  Action, Adventure, Shounen, Supernatural     TV       12    8.17   515378
346                                                Dragon Ball            Adventure, Comedy, Fantasy, Martial Arts, Shounen, Super Power     TV      153    8.16   316102
374                                                Log Horizon                          Action, Adventure, Fantasy, Game, Magic, Shounen     TV       25    8.14   387100
401        Yahari Ore no Seishun Love Comedy wa Machigatteiru.                                            Comedy, Drama, Romance, School     TV       13    8.12   353876
411                                      Byousoku 5 Centimeter                                             Drama, Romance, Slice of Life  Movie        3    8.10   324035
440                                                 Soul Eater                 Action, Adventure, Comedy, Fantasy, Shounen, Supernatural     TV       51    8.08   580184
445                                           Mirai Nikki (TV)           Action, Mystery, Psychological, Shounen, Supernatural, Thriller     TV       26    8.07   657190
449                                                Tokyo Ghoul       Action, Drama, Horror, Mystery, Psychological, Seinen, Supernatural     TV       12    8.07   618056
456                                                       FLCL                           Action, Comedy, Dementia, Mecha, Parody, Sci-Fi    OVA        6    8.06   305165
458                                               Kuroshitsuji        Action, Comedy, Demons, Fantasy, Historical, Shounen, Supernatural     TV       24    8.06   424919
466                                 Suzumiya Haruhi no Yuuutsu                    Comedy, Mystery, Parody, School, Sci-Fi, Slice of Life     TV       14    8.06   428569
491                                        Hataraku Maou-sama!                                 Comedy, Demons, Fantasy, Romance, Shounen     TV       13    8.03   409037
583                             Chuunibyou demo Koi ga Shitai!                             Comedy, Drama, Romance, School, Slice of Life     TV       12    7.95   394399
582                                                     Bleach                        Action, Comedy, Shounen, Super Power, Supernatural     TV      366    7.95   624055
615                                         Naruto: Shippuuden                        Action, Comedy, Martial Arts, Shounen, Super Power     TV  Unknown    7.94   533578
644                                                   Claymore    Action, Adventure, Demons, Fantasy, Shounen, Super Power, Supernatural     TV       26    7.92   316853
643                                             Ao no Exorcist                            Action, Demons, Fantasy, Shounen, Supernatural     TV       25    7.92   583823
659                                                  Charlotte                                                Drama, School, Super Power     TV       13    7.91   310137
665                                                    Nisekoi                                   Comedy, Harem, Romance, School, Shounen     TV       20    7.91   347599
708   Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka                               Action, Adventure, Comedy, Fantasy, Romance     TV       13    7.88   336349
713                                          Kyoukai no Kanata                                      Fantasy, Slice of Life, Supernatural     TV       12    7.88   359011
702                                                    Another                           Horror, Mystery, School, Supernatural, Thriller     TV       12    7.88   534657
729                                                 Lucky☆Star                                     Comedy, Parody, School, Slice of Life     TV       24    7.87   305837
727                                                      K-On!                                      Comedy, Music, School, Slice of Life     TV       13    7.87   386048
760                                                 Elfen Lied       Action, Drama, Horror, Psychological, Romance, Seinen, Supernatural     TV       13    7.85   623511
775                                             Akame ga Kill!                                                Action, Adventure, Fantasy     TV       24    7.84   492133
804                                           Sword Art Online                                 Action, Adventure, Fantasy, Game, Romance     TV       25    7.83   893100
841                                                     Naruto                        Action, Comedy, Martial Arts, Shounen, Super Power     TV      220    7.81   683297
830                                               Guilty Crown                                        Action, Drama, Sci-Fi, Super Power     TV       22    7.81   460959
922                                     Tonari no Kaibutsu-kun                            Comedy, Romance, School, Shoujo, Slice of Life     TV       13    7.77   349836
1057                                           High School DxD                             Comedy, Demons, Ecchi, Harem, Romance, School     TV       12    7.70   398660
1096                                    Toaru Majutsu no Index                                        Action, Magic, Sci-Fi, Super Power     TV       24    7.69   313114
1104                                                   Btooom!                                     Action, Psychological, Sci-Fi, Seinen     TV       12    7.68   329561
1172                                           Owari no Seraph                             Action, Drama, Shounen, Supernatural, Vampire     TV       12    7.65   315630
1183                                                  Hellsing                             Action, Horror, Seinen, Supernatural, Vampire     TV       13    7.64   308995
1220                                               Accel World                                     Action, Game, Romance, School, Sci-Fi     TV       24    7.62   324284
1246                                          Zero no Tsukaima  Action, Adventure, Comedy, Ecchi, Fantasy, Harem, Magic, Romance, School     TV       13    7.62   346828
1338                                           Fate/stay night                             Action, Fantasy, Magic, Romance, Supernatural     TV       24    7.58   374880
1349                              Boku wa Tomodachi ga Sukunai              Comedy, Ecchi, Harem, Romance, School, Seinen, Slice of Life     TV       12    7.57   325664
1518                                            Tokyo Ghoul √A       Action, Drama, Horror, Mystery, Psychological, Seinen, Supernatural     TV       12    7.52   408357
1598               Ore no Imouto ga Konnani Kawaii Wake ga Nai                                             Comedy, Seinen, Slice of Life     TV       12    7.49   321477
1620                                        Deadman Wonderland                                                    Action, Horror, Sci-Fi     TV       12    7.48   453454
1709                                    Highschool of the Dead                                       Action, Ecchi, Horror, Supernatural     TV       12    7.46   535892
1779                                              Black Bullet                                           Action, Mystery, Sci-Fi, Seinen     TV       13    7.44   320267
2132                                       Sword Art Online II                                 Action, Adventure, Fantasy, Game, Romance     TV       24    7.35   537892

In [173]:
top_famous
top_famous.head(100).to_csv("top_famous.csv", index=False)

In [174]:
# This saves the Top 100 rows directly into a clean spreadsheet file on your computer
top_famous.head(100).to_excel("top_100_anime.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'